version: "3.8"

services:
  portfolio_dev_environment:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    privileged: true
    volumes:
      - ..:/workspace:cached
      - portfolio_node_modules:/workspace/node_modules
    ports:
      - "5173:5173"
    command: sleep infinity

volumes:
  portfolio_node_modules:
